### ISSUE TITLE
migrate in memory database to postgres database for all services. All services should use one db called rentaldb

### ISSUE THREAD

**Issue by JeffDropsIT** [Buhle8/microservices#27]
```yaml

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/rentaldb
    username: root
    password: admin
    hikari:
      connection-timeout: 120000
  jpa:
    hibernate:
      use-new-id-generator-mappings: true
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
```
